export * from "./FixComponents/Navbar";
export * from "./Intro";
export * from "./Introduction";
export * from "./HalfCircle";
export * from "./CircleUnderContent";
export * from "./Circle";
export * from "./different";
export * from "./FixComponents";
export * from "./Content";
